# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: GodotEngine.GodotEngine.Mono
PackageVersion: 4.1.2
InstallerType: zip
NestedInstallerType: portable
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: Godot_v4.1.2-stable_mono_win32\Godot_v4.1.2-stable_mono_win32.exe
    PortableCommandAlias: godot
  - RelativeFilePath: Godot_v4.1.2-stable_mono_win32\Godot_v4.1.2-stable_mono_win32_console.exe
    PortableCommandAlias: godot_console
  InstallerUrl: https://github.com/godotengine/godot/releases/download/4.1.2-stable/Godot_v4.1.2-stable_mono_win32.zip
  InstallerSha256: 02487A769B8615EFA3922679246B91495FCA57B63799C27115CDABD2BE35A933
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: Godot_v4.1.2-stable_mono_win64\Godot_v4.1.2-stable_mono_win64.exe
    PortableCommandAlias: godot
  - RelativeFilePath: Godot_v4.1.2-stable_mono_win64\Godot_v4.1.2-stable_mono_win64_console.exe
    PortableCommandAlias: godot_console
  InstallerUrl: https://github.com/godotengine/godot/releases/download/4.1.2-stable/Godot_v4.1.2-stable_mono_win64.zip
  InstallerSha256: 42E0828E886A5809CFC4F3B38578EB5232568706E2A3F01CC4BD06B323D864C1
ManifestType: installer
ManifestVersion: 1.5.0
